### ISSUE TITLE
The Cypress port could not be resolved

### ISSUE THREAD

**Issue by JerWeber** [mfrachet/cypress-audit#158] opened 2022-05-31 09:07 UTC
Hi,

I am trying to use the plugin but I keep on getting this error:

CypressError: `cy.task('lighthouse')` failed with the following error:

```
https://on.cypress.io/api/task
    at http://localhost:4502/__cypress/runner/cypress_runner.js:167117:78
    at tryCatcher (http://localhost:4502/__cypress/runner/cypress_runner.js:13022:23)
    at Promise._settlePromiseFromHandler (http://localhost:4502/__cypress/runner/cypress_runner.js:10957:31)
    at Promise._settlePromise (http://localhost:4502/__cypress/runner/cypress_runner.js:11014:18)
    at Promise._settlePromise0 (http://localhost:4502/__cypress/runner/cypress_runner.js:11059:10)
    at Promise._settlePromises (http://localhost:4502/__cypress/runner/cypress_runner.js:11135:18)
    at _drainQueueStep (http://localhost:4502/__cypress/runner/cypress_runner.js:7729:12)
    at _drainQueue (http://localhost:4502/__cypress/runner/cypress_runner.js:7722:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4502/__cypress/runner/cypress_runner.js:7738:5)
    at Async.drainQueues (http://localhost:4502/__cypress/runner/cypress_runner.js:7608:14)
From Your Spec Code:
    at Context.eval (http://localhost:4502/__cypress/tests?p=cypress\integration\POC\access.spec.js:189:10)

From Node.js Internals:
  Error: The Cypress port could not be resolved. Have you setup the project following this guide: https://github.com/mfrachet/cypress-audit/blob/master/packages/lighthouse/README.md#preparing-the-server-configuration ?
      at C:\Users\xdx737\IdeaProjects\master65\aem-v3\node_modules\@cypress-audit\lighthouse\src\task.js:36:11
      at lighthouse (C:\Users\xdx737\IdeaProjects\master65\aem-v3\cypress\plugins\index.js:53:34)
      at invoke (C:\Users\xdx737\AppData\Local\Cypress\Cache\9.7.0\Cypress\resources\app\packages\server\lib\plugins\child\task.js:46:14)
      at C:\Users\xdx737\AppData\Local\Cypress\Cache\9.7.0\Cypress\resources\app\packages\server\lib\plugins\util.js:45:14
      at tryCatcher (C:\Users\xdx737\AppData\Local\Cypress\Cache\9.7.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\util.js:16:23)
      at Function.Promise.attempt.Promise.try (C:\Users\xdx737\AppData\Local\Cypress\Cache\9.7.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\method.js:39:29)
      at Object.wrapChildPromise (C:\Users\xdx737\AppData\Local\Cypress\Cache\9.7.0\Cypress\resources\app\packages\server\lib\plugins\util.js:44:23)
      at Object.wrap (C:\Users\xdx737\AppData\Local\Cypress\Cache\9.7.0\Cypress\resources\app\packages\server\lib\plugins\child\task.js:52:8)
      at execute (C:\Users\xdx737\AppData\Local\Cypress\Cache\9.7.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:131:19)
      at EventEmitter.<anonymous> (C:\Users\xdx737\AppData\Local\Cypress\Cache\9.7.0\Cypress\resources\app\packages\server\lib\plugins\child\run_plugins.js:213:5)
      at EventEmitter.emit (node:events:520:28)
      at process.<anonymous> (C:\Users\xdx737\AppData\Local\Cypress\Cache\9.7.0\Cypress\resources\app\packages\server\lib\plugins\util.js:19:22)
      at process.emit (node:events:520:28)
      at emit (node:internal/child_process:938:14)
      at processTicksAndRejections (node:internal/process/task_queues:84:21)

> The Cypress port could not be resolved. Have you setup the project following this guide: https://github.com/mfrachet/cypress-audit/blob/master/packages/lighthouse/README.md#preparing-the-server-configuration ?
```

I have followed the project setup page, looked up what others are doing but I keep on getting the error no matter what I try. I am not sure it is really related to a port issue as I tried to setup a port manually in cypress.json and it dit not solve my issue.

I have a few other plugins installed (axe, grep, image-diff-js and mochawesome reporter) but it doesn't look like a conflict between plugins.

Can someone help me ?

I am using Cypress 9.7.0

**Comment by mfrachet** [comment] 2022-06-01 05:40
Could you, please, provide a reproduction of this bug in a dedicated repo so that I can investigate? 😊

**Comment by mfrachet** [comment] 2022-06-29 21:10
I'm closing this issue since there were no answers for a while. Also, the library has been updated for usage with cypress 10. Make sure to take a look at the doc if it may be helpful in some ways :)

**Closed by mfrachet** 2022-06-29 21:10 UTC
Labels: bug

**Comment by tsvetya** [comment] 2022-07-21 11:33
Hi, I have the same issue with cypress 10.3.1
this is a simplified version of the project where I reproduce it: https://github.com/tsvetya/demo-cypress-lighthouse 
I could open a new issue if you prefer it.
<img width="907" alt="image" src="https://user-images.githubusercontent.com/7148241/180203705-04bc62dd-87f2-45be-a31a-069b2e272431.png">
