### ISSUE TITLE
Error : You probably have multiple tabs open to the same origin

### ISSUE THREAD

**Issue by thaiching** [mfrachet/cypress-audit#113] opened 2021-10-06 12:47 UTC
Hi,
  This issue probably has been raised before here but I couldn't find any concrete workaround to fix this. I'm encountering this issue as well when I tried to integrate my Cypress test with cypress-audit plugin.

   I'm getting the following error when I tried to run my tests using Cypress test runner tool or running the test in headless mode.

<img width="807" alt="Untitled" src="https://user-images.githubusercontent.com/7057586/136203139-8bf8ec92-7299-4f66-bf81-5fe43ae2d5d2.png">

  Here are the code snippet from the index.js file and my spec file

**plugins/index.js**
```
const del = require('del');
const fs = require('fs-extra');
const path = require('path');
const installLogsPrinter = require('cypress-terminal-report/src/installLogsPrinter');
const { lighthouse, pa11y, prepareAudit } = require('cypress-audit');

const getConfigurationByFile = (file) => {
  const pathToConfigFile = `config/cypress.${file}.json`;
  return !!file && fs.readJson(path.join(__dirname, '../', pathToConfigFile));
};

module.exports = (on, config) => {
  installLogsPrinter(on, {
    printLogsToConsole: 'onFail',
    collectTestLogs: () => console.log(''),
  });

  on('before:browser:launch', (browser = {}, launchOptions) => {
    prepareAudit(launchOptions);
    return launchOptions;
  });

  on('after:spec', (spec, results) => {
    if (results && results.video) {
      // Do we have failures for any retry attempts?
      const failures = results.tests.some((test) => {
        return test.attempts.some((t) => t.state === 'failed');
      });

      if (!failures) {
        // delete the video if the spec passed and no tests retried
        return del(results.video);
      }
    }
  });

  on('task', {
    lighthouse: lighthouse(),
    pa11y: pa11y(),
  });

  return getConfigurationByFile(config.env.platform) || config;
};

```

My Spec file

```
describe.only('Lighthouse', () => {
    it('should run performance audits', () => {
      cy.visit('/');
      cy.lighthouse();
    });
 });
```

I've also imported this line of code in my **commands.ts** file
`import "cypress-audit/commands";`

Cypress version : Tried both 7.7.0 and 6.9.1
Cypress-audit version : 1.0.0
Chrome version : 94
Mac OS Catalina 10.15.1

**Comment by mfrachet** [comment] 2021-10-06 12:58
Could you try to bump on v1.1.0 ?

Do you have a tab opened on chrome with the concerned URL?

**Comment by thaiching** [comment] 2021-10-06 14:30
I tried version v1.1.0 too and still having the same issue. :(

I don't have any browser/tabs opened with the testing URL when the tests are run.

**Comment by mfrachet** [comment] 2021-10-06 14:32
And can you try with Cypress 8+ ? I remember there was an issue in cypress that was failing when trying to connect to the chrome devtool protocol

**Comment by thaiching** [comment] 2021-10-06 14:46
Hi, I tried the latest Cypress version 8.5.0 but still having the same issue. :(

**Comment by mfrachet** [comment] 2021-10-11 07:35
Looks it should be feasible with something like https://gist.github.com/jamesfulford/26181c332c25d6464c3524510d18e75e

**Comment by mfrachet** [comment] 2021-12-01 09:29
Have you been able to fix the issue?

**Comment by MuckT** [comment] 2021-12-04 07:46
@thaiching you could try this https://github.com/cypress-io/cypress/issues/8801#issuecomment-706224809.

**Comment by mattvb91** [comment] 2022-02-17 07:15
I am having this issue on cypress 9.4.1 with this package at 1.1.0. Couldn't get it resolved with the linked fixes above.

**Comment by mxkyb** [comment] 2022-02-22 12:44
Same problem on cypress 8.5.0 and cypress-audit `1.1.0`.

**Comment by mfrachet** [comment] 2022-02-23 05:41
Closing, since it's seems related to the service worker. Feel free to reopen **with a reproducible example** so that I can check. Thanks for the help 🙏🏻

**Closed by mfrachet** 2022-02-23 05:41 UTC
Labels: bug
