### ISSUE TITLE
v10.1.0 node_modules/@cypress-audit/lighthouse/index.d.ts' is not a module.ts(2306)`

### ISSUE THREAD

**Issue by dante01yoon** [mfrachet/cypress-audit#166] opened 2022-06-17 06:34 UTC
**What does not work?**

Hi, I'm using v10.1.0, typescript v4.7.2 
from v10, all the environment config settings are done in `cypress.config.ts`, which means I import all modules of cypress-audit in cypress.config.ts.

it gives me ts error.
![스크린샷 2022-06-17 오후 3 27 29](https://user-images.githubusercontent.com/6510430/174239098-874896df-77c0-4d63-8e7e-d70f9b3c22bb.png)

the error message is 
`front-e2e-test/node_modules/@cypress-audit/lighthouse/index.d.ts' is not a module.ts(2306)`

I',m not sure problem occurs from index.d.ts under @cypress-audit/lighthouse, 
![스크린샷 2022-06-17 오후 3 32 45](https://user-images.githubusercontent.com/6510430/174239268-ce146b2a-695c-4ede-8898-1fcc55f518c3.png)

**How to reproduce?**
import lighthouse in cypress.config.ts

**Expected behavior**

**Screenshots / Animated Gifs**
Add screenshots or screen recordings to help explain your problem.

**Environment (please complete the following information):**
 - OS: mac os 
 - Chrome version: vscode, not chrome
 - Cypress version: v10.1.0

**Any other information that may help fixing the issue?**

**Comment by mfrachet** [comment] 2022-06-18 07:40
Closing, seems duplicate of https://github.com/mfrachet/cypress-audit/issues/162

**Closed by mfrachet** 2022-06-18 07:40 UTC
Labels: bug
