### ISSUE TITLE
 CypressError: `cy.task('lighthouse')` failed with the following error:  > connect ECONNREFUSED ::1:60387

### ISSUE THREAD

**Issue by yorgosper** [mfrachet/cypress-audit#136] opened 2022-03-17 12:10 UTC
**What does not work?**
Trying to run examples/external-url locally I am getting a connection error.

**How to reproduce?**
Execute test in examples/external-url

**Screenshots / Animated Gifs**
![Screenshot 2022-03-17 at 1 55 58 PM](https://user-images.githubusercontent.com/85868845/158803538-5cba4617-9af7-455c-b4e1-e60a53af3177.png)

**Environment (please complete the following information):**
 - OS: MacOS 12.2
 - Chrome version: 99
 - Cypress version: 9.5.2

**Any other information that may help fixing the issue?**
Read the comment here https://github.com/mfrachet/cypress-audit/issues/62 but could not find a solution.

**Comment by addicus** [comment] 2022-03-22 12:41
Same issue for me

**Comment by mfrachet** [comment] 2022-04-19 06:05
Have you manage to do something on this one?

What's is interesting to me is that the port displayed is not valid 🤔 Like `econnrefused on :1::60387` (which is not a valid port for the browser)

**Comment by Susochat** [comment] 2022-04-19 09:17
Same issue for me from versions 9.1.0+
Working for me for 8.7.0 version and below.

**Comment by mfrachet** [comment] 2022-05-30 15:29
Does this still occurs?

**Comment by Susochat** [comment] 2022-05-31 05:35
Yes it is still occurring in cypress 9.7.0 version.

**Comment by mfrachet** [comment] 2022-05-31 05:56
Any possibility to share an open source repo reproducing the error ?

**Comment by MichaelRobsonSliide** [comment] 2022-06-17 12:23
I'm also getting this same error:
<img width="685" alt="Screenshot 2022-06-17 at 13 20 00" src="https://user-images.githubusercontent.com/105351306/174297148-204283c5-c27e-4444-9e21-caf9f8ca7eaf.png">

I'm using a higher version of Cypress:
```
"cypress": "^10.1.0",
"cypress-audit": "^1.1.0",
```
To get cypress-audit working with cypress 10 I followed the changes in this open [PR](https://github.com/mfrachet/cypress-audit/pull/156/files)

**Comment by mfrachet** [comment] 2022-06-29 21:11
@MichaelRobsonSliide , the library is now `@cypress-audit/lighthouse` and is in version 1.3.1. The doc website has been updated accordingly. Do you mind checking it and see if it solves your problem or not?

**Comment by MichaelRobsonSliide** [comment] 2022-06-30 10:27
> @cypress-audit/lighthouse

Thanks, I've just followed the doc but I get an error when opening Cypress saying pa11y isn't defined:

> Your configFile threw an error from: /.../cypress.config.js
> 
> The error was thrown while executing your e2e.setupNodeEvents() function:
> 
> cypress.config.js:19:16
>   17 |       on('task', {
>   18 |         lighthouse: lighthouse(),
> > 19 |         pa11y: pa11y(console.log.bind(console)),
>      |                ^
>   20 |       })
>   21 |     },

**Comment by MichaelRobsonSliide** [comment] 2022-06-30 12:47
> @MichaelRobsonSliide , the library is now `@cypress-audit/lighthouse` and is in version 1.3.1. The doc website has been updated accordingly. Do you mind checking it and see if it solves your problem or not?

Thanks that works fine, one thing it might be worth making clear or updating is this part

>       on("task", {
>         lighthouse: lighthouse(),
>         pa11y: pa11y(console.log.bind(console)),
>       });

From https://mfrachet.github.io/cypress-audit/guides/lighthouse/installation.html#the-server-configuration this will fail until you also follow the pa11y install part of the doc to add @cypress-audit/pa11y.

The Pa11y part of the guide does not assume lighthouse is installed so none of the examples make reference to it but the lighthouse part assumes you have the pa11y dependency.

**Comment by mfrachet** [comment] 2022-07-01 05:54
Have you tried with the instructions here https://mfrachet.github.io/cypress-audit/guides/pa11y/installation.html#the-server-configuration ?

**Comment by MichaelRobsonSliide** [comment] 2022-07-01 08:16
Yes, I followed the instructions for pa11y and lighthouse, I get the same webSocket error if I try to run pa11y against my test domain or google. 

This is my cypress config file

```
const { defineConfig } = require('cypress')

const { lighthouse, prepareAudit } = require('@cypress-audit/lighthouse')
const { pa11y } = require('@cypress-audit/pa11y')

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      require('cypress-mochawesome-reporter/plugin')(on)

      on('before:browser:launch', (browser = {}, launchOptions) => {
        prepareAudit(launchOptions)
      })

      on('task', {
        lighthouse: lighthouse(),
        pa11y: pa11y(),
      })
    },

    // Global Cypress configuration settings
    baseUrl: '*MYSITE*',
    video: true,
    chromeWebSecurity: false,
    retries: {
      runMode: 3,
      openMode: 0,
    },

    // Report config
    reporter: 'cypress-mochawesome-reporter',
    reporterOptions: {
      reportDir: 'cypress/reports',
      charts: true,
      embeddedScreenshots: true,
      inlineAssets: true,
    },
  },
})
```

**Comment by bode-praetorian** [comment] 2022-07-19 14:32
Getting the same task failure in Cypress 10.2.0. I run:
`import "@cypress-audit/lighthouse/commands";

describe('CA Lighthouse Test', () => {
    before(() => {
        cy.loginAlt('ca')
    })

  it('Compare first paint', () => {

    const customThresholds = {
        performance: 50,
        accessibility: 50,
        seo: 70,
        'first-contentful-paint': 2000,
        'largest-contentful-paint': 3000,
        'cumulative-layout-shift': 0.1,
        'total-blocking-time': 500,
      };
  
      const desktopConfig = {
        formFactor: 'desktop',
        screenEmulation: {
            mobile: false,
            disable: false,
            width: Cypress.config('viewportWidth'),
            height: Cypress.config('viewportHeight'),
            deviceScaleRatio: 1,
          }
      };

      cy.visit('/', {timeout: 20000}).then(() => {
        //cy.lighthouse(customThresholds, desktopConfig)
        cy.lighthouse()
      })
    })
})`

and get index.fd56be2f.js:65032 CypressError: `cy.task('lighthouse')` timed out after waiting `60000ms`. I followed the instructions as well:

`const { defineConfig } = require('cypress')
const { lighthouse, prepareAudit } = require("@cypress-audit/lighthouse");
const { pa11y } = require("@cypress-audit/pa11y");

module.exports = defineConfig({
  retries: {
    runMode: 2,
    openMode: 0,
  },
  e2e: {
    experimentalSessionAndOrigin: true,
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      on("before:browser:launch", (browser = {}, launchOptions) => {
        prepareAudit(launchOptions);
      });
      on("task", {
        lighthouse: lighthouse(),
        pa11y: pa11y(console.log.bind(console)),
      });
      return (on, config)
    },
    defaultCommandTimeout: 8000,
    execTimeout: 60000,
    taskTimeout: 60000,
    pageLoadTimeout: 60000,
    requestTimeout: 8000,
    responseTimeout: 30000,
  },
})`

**Comment by juanduarte1927** [comment] 2022-09-09 17:06
I have the same issue
@cypress-audit/lighthouse = 1.3.1
cypress version 9.7.0

The difference for me is that I can run locally the plugin, but when I launch the automated scenarios on Browser Stack, appear the error **_connect ECONNREFUSED ::1:60387_**
I was wondering if the plugin has support to run on Browser Stack. Thank you for your answer

**Comment by RJKeane2000** [comment] 2022-11-10 05:07
I ran into the same thing running on Windows locally. According to this [StackOverflow article](https://stackoverflow.com/questions/72648487/node-js-16-17-changed-resolution-of-localhost), starting in Node 17, 

`Node.js no longer re-sorts results of IP address lookups and returns them as-is (i.e. it no longer ignores how your OS has been configured)`

On my Windows laptop, localhost is resolving to it's IPV6 address of ::1. You can see that in @juanduarte1927's comment above as well. I wasn't able to figure out a way to pass the --dns-result-order option to Node when I launch Cypress but was looking at the code for @cypress-audit/pa11y.  In the task.js, I changed localhost to 127.0.0.1 and my tests worked.  I'm not sure if this is a practical solution or not. Would it be the same on Macs?  Here's what the task.js looks like with my change:

`const pa11yLib = require("pa11y");
const puppeteer = require("puppeteer");

const pa11y = (callback) => async ({ url, opts }) => {
  const browser = await puppeteer.connect({
    browserURL: `http://127.0.0.1:${global.cypress_audit_port}`,
  });

  const results = await pa11yLib(url, { browser, runners: ["axe"], ...opts });

  if (callback) {
    callback(results);
  }

  return results.issues || [];
};

module.exports = { pa11y };
`

**Versions**:
Cypress:        11.0.0                                                                         │
Browser:        Chrome 106 (headless)                                                          │
Node Version:   v19.0.0 (C:\Program Files\nodejs\node.exe)                                     │
@cypress-audit:  1.3.1

**Comment by RJKeane2000** [comment] 2022-11-11 05:08
I was able to find a workaround that's not too bad.  I set NODE_OPTIONS="--dns-result-order=ipv4first".  This appears to be backwards compatible. I ran this with Node 16 (Linux) as well as Node 19 (Windows). To simplify things, I added a script in my package.json to look like this:

```json
"cypress:open": "cross-env NODE_OPTIONS=--dns-result-order=ipv4first && cypress open",
"cypress:e2e-chrome-reports": "cross-env NODE_OPTIONS=--dns-result-order=ipv4first cypress run --headless --browser=chrome && npx mochawesome-merge 'cypress/results/*.json' > mochawesome.json && npx marge mochawesome.json"
```

I used the cross-env package to make it work across platforms, Mac, Windows and Linux. I'll have a buddy try it out on his Mac tomorrow with Node 19 just to make sure it works.

Thanks for the work you do to support and improve cypress-audit!

**Comment by KadirAtug07** [comment] 2022-11-18 20:00
I NEED HELP!!! I've integrated lighthouse to Cypress but I'm getting cy.task('lighthouse') failed. it works when I use headless mode with this implementation 
```
module.exports = async (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    prepareAudit(launchOptions);
    allureWriter(on, config);
  });

  on('task', {
    lighthouse: lighthouse(), // calling the function is important
    pa11y: pa11y(console.log.bind(console)),
  });
  if (config.testingType === 'component') {
    config.viewportHeight = allSizes[4][0];
    config.viewportWidth = allSizes[4][1];
    require('@cypress/react/plugins/next')(on, config);
  }
  return config;
};
```
But I am giving tags to my test cases so it's like 
const tagify = require("cypress-tags");
`module.exports = async (on, config) => {
  on('file:preprocessor', **tagify(config)**, (browser = {}, launchOptions) => {
    prepareAudit(launchOptions);
    allureWriter(on, config);
  });

  on('task', {
    lighthouse: lighthouse(), // calling the function is important
    pa11y: pa11y(console.log.bind(console)),
  });
  if (config.testingType === 'component') {
    config.viewportHeight = allSizes[4][0];
    config.viewportWidth = allSizes[4][1];
    require('@cypress/react/plugins/next')(on, config);
  }
  return config;
};`
So My Question is HOW CAN I IMPLEMENT TAG WITH LIGHHOUSE?

**Comment by bvandercar-vt** [comment] 2023-03-10 01:19
> ```json
> result-or
> ```

please create a new question thread, not relevant to the question at hand.

**Comment by mfrachet** [comment] 2023-03-23 06:15
https://github.com/mfrachet/cypress-audit/issues/136#issuecomment-1311236777 by forcing ipv4 in nodejs instead of ipv6

Seems to be a valid fix for this one. I m closing. Feel free to reopen if needed

**Closed by mfrachet** 2023-03-23 06:15 UTC
Labels: bug
